[package]
name = "rdweek"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ed25519-dalek = "2"
serde = "1.0.197"
hex = "0.4"
tokio = { version = "1", features = ["full"] }
